### PR TITLE
[Webinterface] Only allow certain characters in the handle 

### PR DESCRIPTION
**Pull request by CKH4**
Still need to discuss how to handle illegal characters. I personally favor replacing whitespace with "_" and stripping the rest but the downside is that this is added complexity which may not be expected.

### CODE REVIEW

**Comment by CKH4** [comment]
These changes shouldn't affect retrieving existing files (I think) but we need to be careful not to change the way handles are handled in a way that would disable handles with illegal characters

**Comment by rfornea** [comment]
@AaronVasquez  In your opinion how should we handle illegal characters in a filename?  I lean towards just replacing everything illegal (whether it's a whitespace or something else) with underscores.

**Comment by AaronVasquez** [comment]
I think either replacing or stripping all illegal characters would make sense. There's no real benefit to treat some special illegal characters differently IMO.

Which characters are considered valid? Are we limiting to just ascii?

**Comment by rfornea** [comment]
The only valid characters will be letters, numbers, dashes, and underscores.

**Comment by CKH4** [comment]
Maybe we should consider removing by group (`/[^\w-]+/`)? This would give more information in files with multiple illegal characters (ie. `"mac & cheese" -> "mac_cheese"` instead of `-> "mac___cheese"`). Just a small thing to consider.

**Comment by rfornea** [comment]
@CKH4  Removing by group sounds good.

**Pull request merged**
